/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *  
 *  http://aws.amazon.com/apache2.0
 *  
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package software.amazon.awssdk.enhanced.dynamodb.extensions;

import java.util.HashMap;
import java.util.Map;
import software.amazon.awssdk.enhanced.dynamodb.AttributeConverter;
import software.amazon.awssdk.enhanced.dynamodb.AttributeValueType;
import software.amazon.awssdk.enhanced.dynamodb.EnhancedType;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;

public class NestedItemAttributeConverter implements AttributeConverter<AutoGeneratedUuidExtensionTest.NestedItem> {

    @Override
    public AttributeValue transformFrom(AutoGeneratedUuidExtensionTest.NestedItem input) {
        Map<String, AttributeValue> map = new HashMap<>();
        map.put("uuid", AttributeValue.builder().s(input.getUuid()).build());
        return AttributeValue.builder().m(map).build();
    }

    @Override
    public AutoGeneratedUuidExtensionTest.NestedItem transformTo(AttributeValue input) {
        AutoGeneratedUuidExtensionTest.NestedItem nestedItem = new AutoGeneratedUuidExtensionTest.NestedItem();
        nestedItem.setUuid(input.m().get("uuid").s());
        return nestedItem;
    }

    @Override
    public EnhancedType<AutoGeneratedUuidExtensionTest.NestedItem> type() {
        return EnhancedType.of(AutoGeneratedUuidExtensionTest.NestedItem.class);
    }

    @Override
    public AttributeValueType attributeValueType() {
        return AttributeValueType.M;
    }
}